sudo: required
services:
  - docker

before_install:
  - docker build -t moylette/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run moylette/react-test npm test -- --coverage

after_success:
  - docker build -t moylette/multi-client ./client
  - docker build -t moylette/multi-nginx ./nginx
  - docker build -t moylette/multi-server ./server
  - docker build -t moylette/multi-worker ./worker
#Login to dockerhub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#Push images to dockerhub
  - docker push moylette/multi-client
  - docker push moylette/multi-nginx
  - docker push moylette/multi-server
  - docker push moylette/multi-worker

deploy:
- provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "multi-dockerr"
  env: "MultiDockerr-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-785468393901"
  bucket_path: "docker-multi"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY